### ISSUE TITLE
type casting and inheritdoc

### ISSUE THREAD

**Issue by pavarnos** [sunrise-php/http-header-kit#7]
Hi. Thanks for http-header-kit. Tons of handy tools in here.
A couple of related questions

https://github.com/sunrise-php/http-header-kit/blob/master/src/AbstractHeader.php#L26 has `@inheritdoc` but it does not inherit from anything. 

If I do something like this
```php
$handler = new class implements RequestHandlerInterface {
    public function handle(\Psr\Http\Message\ServerRequestInterface $request): \Psr\Http\Message\ResponseInterface
    {
        $response = new \GuzzleHttp\Psr7\Response(200, [], 'Hello world');
        $response = (new \Sunrise\Http\Header\HeaderContentType('text/plain'))->setToMessage($response);
        return $response;
    }
};
```
phpstan and phpStorm both complain that `$response` is a MessageInterface instead of a ResponseInterface

Would you consider changing the return types in AbstractHeader to eg
```php
	/**
	 * @return MessageInterface|RequestInterface|ServerRequestInterface|ResponseInterface
	 */
	public function setToMessage(MessageInterface $message);
```
to keep these tools happy?

or (alternatively) providing strictly typed variants eg
```php
	/**
	 * @return ServerRequestInterface
	 */
	public function setToServerRequest(ServerRequestInterface $message): ServerRequestInterface;
```
and similar for MessageInterface, ResponseInterface, RequestInterface etc

**Comment by peter279k** [comment]
That's right.

The `AbstractHeader` class doesn't inherit any interface or class.

And it should let the abstract methods have the correct return type hint annotation.

**Comment by pavarnos** [comment]
ah. i see. then maybe https://github.com/sunrise-php/http-header-kit/blob/master/src/AbstractHeader.php#L22 should be
```php
abstract class AbstractHeader implements HeaderInterface
```
?
So that the `@inheritdoc` will work? This will solve part of the problem above...

**Comment by peter279k** [comment]
As @pavarnos says, `AbstractHeader` class misses the `implement HeaderInterface`.

It will be correct and `@inheritdoc` should be worked successfully.

**Comment by fenric** [comment]
@pavarnos Hello, can try version v1.0.6

**Comment by peter279k** [comment]
It looks good to me on version `v1.0.6`.

**Comment by pavarnos** [comment]
thank you. getting closer.

Now we need something like #8 to help us keep strict type checking tools like phpStan or phpStorm happy. Would you accept a pull request for #8?

**Comment by fenric** [comment]
> Now we need something like #8 to help us keep strict type checking tools like phpStan or phpStorm happy. Would you accept a pull request for #8?

@pavarnos yes of course. Must be the same code style. Your solution should be covered by tests. Do you want to send a pull request?
