### ISSUE TITLE
Helper method for many headers

### ISSUE THREAD

**Issue by pavarnos** [sunrise-php/http-header-kit#8]
What do you think about a helper method that takes your classes and returns an array of formatted headers suitable for the `ServerRequest`? 

```php
$headers = \Sunrise\Http\Headers::make([
    new HeaderCookie('whatever'),
    new HeaderContentEncoding('multipart/form-data')
    new HeaderSomethingElse('foo')
]);
$request = new ServerRequest('POST', 'https://example.com', $headers, 'Whatever');
```

**Comment by peter279k** [comment]
It looks like the `Headers` class can collect the all header options and let `ServerRequest` class can be easy to set all allowed headers.

I think it's the one of way to set header options be suitable for `ServerRequest` class.

**Comment by fenric** [comment]
I think you can do this:

```php
// create a new header collection
$headers = new \Sunrise\Http\Header\HeaderCollection([
    new \Sunrise\Http\Header\HeaderContentType('application/json'),
    new \Sunrise\Http\Header\HeaderContentLength(1024),
    new \Sunrise\Http\Header\HeaderSunset(new \DateTime('+1 year')),
]);

// set the collection to a message
$headers->setToMessage($message);
// or
$headers->addToMessage($message);
```
Do you think it would be useful? @pavarnos @peter279k 

---

PSR-7 knows nothing about the Sunrise Header Kit:

```php
$request = new ServerRequest('POST', 'https://example.com', $headers, 'Whatever');
```

... so there may be problems...

**Comment by peter279k** [comment]
@pavarnos, thank you for your reply.

The `\Sunrise\Http\Header\HeaderCollection` class looks fine because it's another way to collect the heders.

**Comment by peter279k** [comment]
> I think you can do this:
> 
> ```
> // create a new header collection
> $headers = new \Sunrise\Http\Header\HeaderCollection([
>     new \Sunrise\Http\Header\HeaderContentType('application/json'),
>     new \Sunrise\Http\Header\HeaderContentLength(1024),
>     new \Sunrise\Http\Header\HeaderSunset(new \DateTime('+1 year')),
> ]);
> 
> // set the collection to a message
> $headers->setToMessage($message);
> // or
> $headers->addToMessage($message);
> ```
> 
> Do you think it would be useful? @pavarnos @peter279k
> 
> PSR-7 knows nothing about the Sunrise Header Kit:
> 
> ```
> $request = new ServerRequest('POST', 'https://example.com', $headers, 'Whatever');
> ```
> 
> ... so there may be problems...

Here is the suggestion about the `Collection`, perhaps we can use the existed `Collection` package, (such as [PHP-Collection](https://jmsyst.com/libs/PHP-Collection)).

@fenric and @pavarnos, what do you think about that?

**Comment by fenric** [comment]
> Here is the suggestion about the `Collection`, perhaps we can use the existed `Collection` package, (such as [PHP-Collection](https://jmsyst.com/libs/PHP-Collection)).
> 
> @fenric and @pavarnos, what do you think about that?

@pavarnos @peter279k 

I think this is very redundant.

I think that several methods are enough for a collection:

```php
/**
 * Constructor of the header collection
 *
 * @param HeaderInterface[] $headers 
 */
public function __construct(iterable $headers = []);

/**
 * Returns the header collection copy with the given header
 */
public function withHeader(HeaderInterface $header) : MessageInterface;

/**
 * Returns the header collection copy with the given added header
 */
public function withAddedHeader(MessageInterface $message) : MessageInterface;

/**
 * Adds all collection headers to the given message
 */
public function addToMessage(MessageInterface $message) : MessageInterface;

/**
 * Sets all collection headers to the given message
 */
public function setToMessage(MessageInterface $message) : MessageInterface;
```

I think that will be enough. What do you think?

**Comment by peter279k** [comment]
@fenric, if we want to keep the `HeaderCollection` class lightweight, this `HeaderCollection` class sample code you mention is good for me.

**Comment by fenric** [comment]
@pavarnos @peter279k https://github.com/sunrise-php/http-header-collection

This is a collection for HTTP headers. Now I am thinking about integrating the collection into the [sunrise/http-message](https://github.com/sunrise-php/http-message)...

Currently I see it as follows:

```php
use Sunrise\Http\Header\HeaderCollection;
use Sunrise\Http\Message\ResponseFactory;

$message = (new ResponseFactory)->createResponse()->withHeaders(new HeaderCollection([
    // headers...
]));
```

What do you think about it?

**Comment by pavarnos** [comment]
Looking good. What is maybe needed is `HeaderCollection->toArray()` or similar so 
```php
$message = (new ResponseFactory)->createResponse()->withHeaders((new HeaderCollection([
    // headers...
]))->toArray());
```
then you can use standard PSR `ResponseInterface` and `ResponseFactory`.

It may also be simpler / cleaner to have HeaderCollection not as a separate component but included within http-header-kit, because it is something you want to do often, does not make sense by itself, is only a single class etc. Once you get projects with 100+ packages, composer starts to run _really_ slow. So it makes sense to me to combine if there is no obvious reason to have them separate.

**Comment by pavarnos** [comment]
... or add a `HeaderCollection::make()` method as in the original suggestion at the top

**Comment by fenric** [comment]
@pavarnos I like the idea with the `toArray` method, it will have to return the following structure:

```php
[
  'x-foo' => [
    'foo',
  ],
  'x-bar' => [
    'bar',
  ],
]
```

The solution to your problem might look like this:

```php
$headers = new HeaderCollection([
    new XFooHeader(),
    new XBarHeader(),
    new XBazHeader(),
]);

$request = new ServerRequest('POST', 'https://example.com/', $headers->toArray());
```

Starting with version `v1.0.10`, `http-header-kit` will be installed automatically with `http-header-collection`. But for now the `http-header-collection` will be as a separate package...

Today I plan to release.

**Comment by fenric** [comment]
@pavarnos I have released version [v1.0.10](https://github.com/sunrise-php/http-header-kit/releases/tag/v1.0.10).

Now the [http-header-kit](https://github.com/sunrise-php/http-header-kit) is installed along with the [http-header-collection](https://github.com/sunrise-php/http-header-collection).

https://github.com/sunrise-php/http-header-kit#http-header-collection

Tell me please, could I help you?

**Comment by pavarnos** [comment]
thank you. Looking good. The 2 separate composer packages will cause some small problems but they can be worked around (eg https://github.com/pavarnos/ComposerRequireChecker will remind me if i use the `HeaderCollection` but forget to `composer require` it).
Thanks for all your work on this.

**Comment by fenric** [comment]
@pavarnos Glad to help you. Thank you for your interest in the project!

**Comment by peter279k** [comment]
According to the `http-header-kit` [README](https://github.com/sunrise-php/http-header-kit), it doesn't have the usage about how to use the `HeaderCollection` to collect the headers `ResponseFactory` class.

**Comment by fenric** [comment]
> According to the `http-header-kit` [README](https://github.com/sunrise-php/http-header-kit), it doesn't have the usage about how to use the `HeaderCollection` to collect the headers `ResponseFactory` class.

Hello! What about this:

```php
$message = $headers->setToMessage($message);
$message = $headers->addToMessage($message);
$headers->toArray();
```

It's enough... The following construction is not standardized:

```php
new ServerRequest('POST', 'https://example.com/', $headers->toArray());
```

Therefore, it cannot be added to the README.

**Comment by peter279k** [comment]
I think it's enough.

This problem has been resolved.
